### ISSUE TITLE
별도의 업로드를 구현 하는데 질문 있습니다.

### ISSUE THREAD

**Issue by JeongByungYeol** [daumkakao/DaumEditor#459]
attachbox를 사용하지 않고 별도의 업로드를 구현 중이며..
업로드 파일마다 별도의 삭제 버튼이 있습니다.
본문에 이미지 추가는 Editor.getSidebar().getAttacher("image").attachHandler 이걸로 해결 했는데,
본문에서 이미지 삭제는 어떻게 하면 되는거죠?;; 아무리 찾아도 못찾겠습니다..

**Comment by k10526** [comment]
본문 이미지를 일괄 삭제하는건가요?

**Comment by k10526** [comment]
답변이 없으셔서 종료 합니다.
