### ISSUE TITLE
수정 할때 글자색이 들어가면 데이터를 안가지고 오는 현상

### ISSUE THREAD

**Issue by wonsun** [daumkakao/DaumEditor#461]
에디터를 이용하여 글 삽입후 출력, 수정이 가능한데,
글을 입력하거나 수정할때, 글자에 다른 속성이 들어가도 상관은 없으나, 글자의 색상이 들어가게되면
수정폼안에 데이터를 못가지고 오는 현상이 발생합니다.

**Comment by ragiragi** [comment]
주신 글만으로는 상황을 유추하기 어려운데요.
재현 가능한 URL과 재현 시나리오를 적어주시면 이해하는데 도움이 될 것 같습니다.

**Comment by k10526** [comment]
@wonsun 답이 없으시면 해당 이슈를 종료 처리 합니다.
