### ISSUE TITLE
SSL 적용 시 오류

### ISSUE THREAD

**Issue by variu** [daumkakao/DaumEditor#463]
안녕하세요. 다음에디터를 적용하였는데

크롬에선 에러가 안나오는데

IE11 에서 할 시

SEC7111: http://test.co.kr/editor/daumeditor/js/editor.js이(가) HTTPS 보안을 위협합니다.

이런식으로 에러가 나옵니다

프로젝트 상 url을 밝히진 못하나 실제로

위에 https:// 가 붙어야되는데 어디에서 변경해야 되는지 모르겠습니다.

editor.html 상에 config 의 txHost에 https// 로 시작하는 경로를 주었으나 마찬가지입니다.

추가로 

IE 개발자 모드에서 나오는 메시지 중 처음 로딩 시 jquery 에러도 발생합니다.

SCRIPT5007: 정의되지 않음 또는 null 참조인 'length' 속성을 가져올 수 없습니다.

	// args is for internal usage only
	each: function( obj, callback, args ) {
		var value,
			i = 0,
			length = obj.length,
			isArray = isArraylike( obj );

위의 부분에서
정의되지 않음 또는 null 참조인 'length' 속성을 가져올 수 없습니다. 

요런식으로 나오네요.. 음..

form name도 맞추었는데 정확한 원인을 알 수가없네요..

ssl이 아닐 시는 아무 문제가 없습니다.

**Comment by ragiragi** [comment]
@k10526 
SSL이슈는 이걸로 생각되는데(테스트필요) 검토 부탁드려요.
https://github.com/ragiragi/DaumEditor/pull/1

**Comment by variu** [comment]
자답입니다. 
타 프로젝트에 투입되면서 jsp상에  Ie 호환 관련
<meta http-equiv="X-UA-Compatible" content="IE=여기" />  태그가
포함되어 있더군요
여기라는 부분에 IE7 이란 설정이 있었는데
IE=edge 라고 해두니 기본적인 동작은 다 합니다.
호환성 부분에서 약간 문제가 생긴듯 하고 
txHost 는 아무값도 없이 하니 잘 되네요.

밑에 null 참조 오류는 jquery 자체 문제로..
jquery 파일을 수정했습니다.

다 제 문제였네요..하하... 그럼 수고하세요!

**Comment by variu** [comment]
아.. 그런데 SSL 일 경우 http://text.com/editor/daumeditor/js/editor.js이(가) HTTPS 보안을 위협합니다.
는 계속 나네요 
이건 한번 확인해보셔야 할 것 같아요.

**Comment by variu** [comment]
또 자답입니다.. 
js와 css import 시키는 부분에 전부 강제로 https://~ 경로로 주었더니 정상으로 되긴 하네요..
로컬테스트할 시 좀 불편하긴 한데.. 여튼 해결했습니다

**Comment by k10526** [comment]
@variu 감사합니다. ^^ 해당 이슈는 종료 합니다.
