### ISSUE TITLE
다음에디터 글 정렬 관련

### ISSUE THREAD

**Issue by rosy353** [daumkakao/DaumEditor#466]
Editor.modify({content:"",attachments:[]});
이런식으로 들어갈때 자동으로 글을 입력 시켰습니다.

이런식으로 컨텐츠가 들어가지 않는 곳에서는 한줄 한줄 글 정렬이 따로 가능한데 

위에 형식으로 자동으로 들어간 곳에서는 글자 정렬이 각각 따로 적용 안되고 

전체글에 적용이 됩니다. 어찌 해야할까요

**Comment by k10526** [comment]
글을 넣으실때 <br>태그로 사용해서 라인을 넣으신건가요?
한 라인별로 정렬을 하실려면 
```
<p>ㅁㅁ</p>
<p>ㄴㄴ</p>
```
이렇게 넣어주셔야 합니다.
