### ISSUE TITLE
다음에디터 적용관련

### ISSUE THREAD

**Issue by rosy353** [daumkakao/DaumEditor#468]
다음에디터를 적용했는데 

익스플로러에서 호환성보기 설정으로 했을때는 잘나오다가 

크롬이나 다른 브라우저로 열었을 경우에는 로딩중이라고만 뜨고 

기능이 동작하지 않습니다.

다른브라우저에 적용하려면 어떤 걸 수정해줘야 사용이 가능할까요?

추가적으로 editor.js 에서 아래와 같은 에러가 발견 됩니다.

 failed to initialize editor. caused by Error: [Exception]Trex.Form : not exist element - tx_editor_form

**Comment by k10526** [comment]
에디터 html을 넣으실때 반드시 form 태그도 추가해 주셔야 합니다.
