### ISSUE TITLE
첨부 이미지 리사이즈와 관련해 문의드립니다.

### ISSUE THREAD

**Issue by yangwoo4u** [daumkakao/DaumEditor#473]
안녕하세요. 다음에디터를 사용하려고 준비 중입니다.
다름이 아니라, 데모 페이지에서는 
사진 버튼을 이용해 이미지를 첨부하면 리사이즈가 가능한데요...
Git에서 받은 소스를 이용해서는 리사이즈가 되지 않습니다.
제가 변경한 부분은 이미지 첨부를 위해 image.html 부분만 수정했습니다.

사용 환경은 MAC의 Chrome 브라우저입니다.
확인 부탁드립니다..

**Comment by k10526** [comment]
7.5버전을 다운 받으시면 리사이즈가 가능합니다. ^^

리사이즈 기능은 7.5부터 가능한거라서요
