### ISSUE TITLE
스크롤링 금지..

### ISSUE THREAD

**Issue by windbug** [daumkakao/DaumEditor#476]
안녕하세요.

에디터창의 크기를 크게 해두면 편하긴 하지만
작게 해두는 경우 스크롤링에 불편한 점이 있어 문의 드립니다.

에디터위에 마우스 오버시 parent 스크롤 금지는 어느 부분을 수정해야하는지요.

**Comment by k10526** [comment]
iframe내부에서 스크롤 할경우 외부스크롤도 적용됩니다. 이는 브라우져 기본기능이므로 에디터 내부에서 제어 할 수 없습니다.
