### ISSUE TITLE
모바일 이미지 첨부 활성화가 안됩니다...

### ISSUE THREAD

**Issue by ehdwlseoeh** [daumkakao/DaumEditor#477]
https://github.com/daumkakao/DaumEditor/issues/268 
https://github.com/daumkakao/DaumEditor/issues/240 

구글링을 통해 두개의 링크를 참고 했고, 
참고해서 대입했으나 적용이 되지않네요..ㅠㅠ 

아래 소스처럼 올리는게 아닌가요? 
다른 객체 안에 toolbar 가 또 들어가야될까요? ㅠㅠ 

해당글의 답변을 보았지만 해결이 되지 않습니다...ㅠㅠ

var config = {
  .... 생략 ....
  toolbar: {
    image: {
      disabledonmobile: false
    }
  }
  .... 생략 ....
};

이렇게 적었습니다..

**Comment by k10526** [comment]
모바일에서 다음에디터 사용시 여러 문제가 있어 현재 모바일에서 다음에디터 사용이 불가능합니다. 7.6이후 버전에서는 해당 기능이 도입될수 있도록 노력하겠습니다.
