### ISSUE TITLE
테이블 선택시 selectcell이 옵저버에서 체크가 되는데요.

### ISSUE THREAD

**Issue by windbug** [daumkakao/DaumEditor#478]
테이블 선택시 selectcell이 옵저버에서 체크가 되는데요.

테이블이 아닌 것이 옵저버에서 체크가 되게 하려면 어떻게 하나요?

즉, 테이블 외부에 포커스가 가게 될 경우를 체크하려면...

**Comment by k10526** [comment]
selectcell이 옵저버에서 체크된다는게 무슨 의미인가요?

**Comment by windbug** [comment]
음.. 그러니까.. 테이블이 선택 될 경우 테이블 편집 메뉴에 display:none -> display:block이 되잖아요.
테이블이 아닌 것이 선택된 경우, 즉 커서가 테이블을 벗어날 경우 테이블 편집 메뉴를 hidden 시키려고 합니다.

**Comment by k10526** [comment]
해당 기능은 쉽게 제공하고자 이리저리 살펴보았지만 현재 구조에서는 어려움이 있습니다. 추후 7.6이후 버전에 해당 기능을 도입하도록 하겠습니다.
