### ISSUE TITLE
에디터 네 XML + XSLT 문서를 불러올 수 있습니까?

### ISSUE THREAD

**Issue by junehyunlee** [daumkakao/DaumEditor#482]
이슈와, google에서 찾아봐도
XML을 불러와 같은 디렉토리 내 XSLT 을 두고
href로 XSLT경로를 줬을 때 XML은 정상적으로 불러오나 XSLT가 적용되지 않습니다.

에디터 내 에서 XML + XSLT를 지원하는지 궁금합니다.

**Comment by k10526** [comment]
지원하지 않습니다.

**Comment by junehyunlee** [comment]
확인해 주셔서 감사합니다.
