### ISSUE TITLE
표삽입시 저장방법

### ISSUE THREAD

**Issue by kimbabsa** [daumkakao/DaumEditor#483]
textarea에 표를 삽입시 칸의수가 많아지면 태그가 너무 길어져서 DB(Oracle)에 저장오류가 발생됩니다. 필드는 varchar2(4000)인데...
저장할 다른방법이 있을지 궁금합니다

**Comment by k10526** [comment]
글쎄요.. 글이 길어져서 db에 저장이 안되는 문제인것 같은데요. 저희쪽에서 해결할 수 없을것 같은데요.
